# Generated by Django 3.0.8 on 2020-08-27 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ownerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='supporterprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_supporter',
        ),
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
        migrations.DeleteModel(
            name='SupporterProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
