# Generated by Django 3.0.8 on 2020-08-28 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200828_0238'),
        ('users', '0006_auto_20200827_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='petlikes',
            field=models.ManyToManyField(related_name='liked_by', related_query_name='pet', to='projects.PetTag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
