# Generated by Django 3.0.8 on 2020-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pettag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettag',
            name='Projectname',
        ),
        migrations.AddField(
            model_name='project',
            name='species',
            field=models.ManyToManyField(related_name='pets', related_query_name='pet', to='projects.PetTag'),
        ),
    ]
