# Generated by Django 3.0.8 on 2020-08-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200828_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='charityregister',
            field=models.IntegerField(),
        ),
    ]
