# Generated by Django 3.0.8 on 2020-09-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200828_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='species',
            field=models.ManyToManyField(related_name='pets', related_query_name='pet_species', to='projects.PetTag'),
        ),
    ]
