# Generated by Django 3.0.8 on 2020-09-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200903_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='species',
            field=models.ManyToManyField(related_name='projects', related_query_name='project', to='projects.PetTag'),
        ),
    ]
